delete from ufo.performance;
commit;
delete from ufo.venue;
commit;
delete from ufo.artist;
commit;
delete from ufo.artist_category;
commit;
delete from ufo.artist_group;
commit;
update ufo.user set creation_user_id=null;
update ufo.user set modification_user_id=null;
delete from ufo.user;
commit;
ALTER TABLE ufo.user AUTO_INCREMENT = 1;
ALTER TABLE ufo.artist AUTO_INCREMENT = 1;
ALTER TABLE ufo.artist_group AUTO_INCREMENT = 1;
ALTER TABLE ufo.artist_category AUTO_INCREMENT = 1;
ALTER TABLE ufo.venue AUTO_INCREMENT = 1;
ALTER TABLE ufo.performance AUTO_INCREMENT = 1;